---
#Call other playbook converted in tasks to create the structure
#- name: Deploy, configure, and populate Postgres 10
#  hosts: database_servers
#  become: true
#  gather_facts: false
# tags:
#    - database_servers 
# tasks:
- import_playbook: tasks/postgresql.yml

#- name: Deploy, configure, and populate flask repo and virtualenv
#  hosts: app_servers
#  become: true
#  gather_facts: false
#  tags:
#    - application_servers
#    - flask
#  tasks:
- import_playbook: tasks/flask.yml
#
#- name: Deploy haproxy load balancer
#  hosts: load_balancers
#  gather_facts: false 
#  become: true
#  tags:
#    - load_balancers
#  tasks:
- import_playbook: tasks/haproxy.yml
- import_playbook: tasks/smoketest.yml   